name: Daily English Notification
on:
  schedule:
    - cron: '0 8,10,12,14,16,18,20 * * *'  # Powiadomienia od 8:00 do 20:00 co 2h UTC
  workflow_dispatch:  # Ręczne uruchomienie

permissions:
  contents: read
  actions: write

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install python-telegram-bot==20.0 openai requests pandas
      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python ./send_notification.py